# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: v0.7.0-1-g4131d40
_src_path: gh:athackst/ci
automerge_mode: native
do_releases: true
release_template: '## What''s changed


    $CHANGES

    '
site_generator: jekyll
