name: HtmlProofer Action
author: athackst
description: Run HtmlProofer

inputs:
  # required inputs
  directory:
    description: The directory to scan
    required: true
    default: "./_site"
  # optional inputs
  allow_hash_href:
    description: Whether `href="#"` anchors are valid
    required: false
  allow_missing_href:
    description: Do not flag a tags missing href
    required: false
  assume_extension:
    description: Automatically add extension (e.g. .html) to file paths, to allow extensionless URLs (as supported by Jekyll 3 and GitHub Pages)
    required: false
  check_favicon:
    description: Check whether favicons are valid
    required: false
  check_links:
    description: Check whether 'a', 'link' elements are working
    required: false
  check_images:
    description: Check whether 'img' elements are working
    required: false
  check_scripts:
    description: Check whether 'script' elements are working
    required: false
  check_opengraph:
    description: Check images and URLs in Open Graph metadata
    required: false
  check_external_hash:
    description: Check whether external anchors exist
    required: false
  check_internal_hash:
    description: Checks whether internal hashes exist (even if the webpage exists)
  check_sri:
    description: Check that `<link>` and `<script>` external resources use SRI
    required: false
  directory_index_file:
    description: Sets the file to look for when a link refers to a directory.
    required: false
  disable_external:
    description: If `true`, does not run the external link checker
    required: false
  enforce_https:
    description: Require that links use HTTPS
    required: false
  extensions:
    description: A list of Strings indicating the file extensions you would like to check (including the dot)
    required: false
  ignore_empty_alt:
    description: If `true`, ignores images with empty/missing alt tags
    required: false
  ignore_files:
    description: A list (new line or comma separated) list of regex or strings containing file paths that are safe to ignore
    required: false
  ignore_empty_mailto:
    description:  If `true`, allows `mailto:` `href`s which do not contain an email address.
    required: false
  ignore_missing_alt:
    description: If `true`, ignores images with missing alt tags
    required: false
  ignore_status_codes:
    description: A list of numbers representing status codes to ignore.
    required: false
  ignore_urls:
    description: A list (new line or comma separated) of Strings or RegExps containing URLs that are safe to ignore.
    required: false
    default: |
      https://fonts.gstatic.com
  ignore_new_files:
    description: Whether to ignore files that are new
    required: false
    default: 'false'
  swap_urls:
    description: Newline-separated list of regex expressions to swap in urls
    required: false
  host:
    description: The host URL of your site
    required: false
    default: ${{ github.repository_owner }}.github.io
  base_path:
    description: The base name of your site
    required: false
    default: /${{ github.event.repository.name }}
  # Hydra options
  max_concurrency:
    description: Maximum number of concurrent requests
    required: false
  # Typhoeus options
  connect_timeout:
    description: HTTP connection timeout
    required: false
  followlocation:
    description: If 'true' will follow redirections
    required: false
  ssl_verifypeer:
    description: If you’re hitting a non-verifiable SSL server then you’ll have to disable peer verification to make SSL work
    required: false
  ssl_verifyhost:
    description: "If you are getting `SSL: certificate subject name does not match target host name` from curl"
    required: false
  timeout:
    description: HTTP request timeout
    required: false
  # Other
  retries:
    description: Number of times to retry checking links
    required: false
    default: 3
  gh_token:
    description: Github token
    required: false
    default: ${{ github.token }}
  # Deprecated
  check_html:
    description: Validate HTML
    required: false
    deprecationMessage: use `check_links`
  check_img_http:
    description: Enforce that images use HTTPS
    required: false
    deprecationMessage: use `check_images`
  empty_alt_ignore:
    description: Allow images with empty alt tags
    required: false
    deprecationMessage: Use `ignore_empty_alt` instead
  missing_alt_ignore:
    description: Allow images with missing alt tags
    required: false
    deprecationMessage: Use `ignore_missing_alt` instead
  url_ignore:
    description: Newline-separated list of URLs to ignore
    required: false
    deprecationMessage: Use `ignore_urls` instead
  url_ignore_re:
    description: Newline-separated list of URL regexes to ignore
    required: false
    deprecationMessage: Use `ignore_urls` instead
  url_swap:
    description: Newline-separated list of regex expressions to swap in urls
    required: false
    deprecationMessage: Use `swap_urls` instead
  internal_domains:
    description: Newline-separated list of internal domains
    required: false
    deprecationMessage: Setting `internal_domains` has been deprecated in htmlproofer
  max_paralell:
    description: Maximum parallel processes
    required: false
    deprecationMessage: Setting `max_paralell` has been deprecated in htmlproofer

runs:
  using: "composite"
  steps:
    - name: Setup Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.3'
        bundler-cache: true

    - name: Run Htmlproofer
      run: ${{ github.action_path }}/entrypoint.sh
      shell: bash
      env:
        INPUT_GH_TOKEN: ${{ inputs.gh_token }}
        INPUT_DIRECTORY: ${{ inputs.directory }}
        INPUT_ALLOW_HASH_HREF: ${{ inputs.allow_hash_href }}
        INPUT_ALLOW_MISSING_HREF: ${{ inputs.allow_missing_href }}
        INPUT_ASSUME_EXTENSION: ${{ inputs.assume_extension }}
        INPUT_CHECK_FAVICON: ${{ inputs.check_favicon }}
        INPUT_CHECK_LINKS: ${{ inputs.check_links }}
        INPUT_CHECK_IMAGES: ${{ inputs.check_images }}
        INPUT_CHECK_SCRIPTS: ${{ inputs.check_scripts }}
        INPUT_CHECK_OPENGRAPH: ${{ inputs.check_opengraph }}
        INPUT_CHECK_EXTERNAL_HASH: ${{ inputs.check_external_hash }}
        INPUT_CHECK_INTERNAL_HASH: ${{ inputs.check_internal_hash }}
        INPUT_CHECK_SRI: ${{ inputs.check_sri }}
        INPUT_DIRECTORY_INDEX_FILE: ${{ inputs.directory_index_file }}
        INPUT_DISABLE_EXTERNAL: ${{ inputs.disable_external }}
        INPUT_ENFORCE_HTTPS: ${{ inputs.enforce_https }}
        INPUT_EXTENSIONS: ${{ inputs.extensions }}
        INPUT_IGNORE_EMPTY_ALT: ${{ inputs.ignore_empty_alt }}
        INPUT_IGNORE_FILES: ${{ inputs.ignore_files }}
        INPUT_IGNORE_EMPTY_MAILTO: ${{ inputs.ignore_empty_mailto }}
        INPUT_IGNORE_MISSING_ALT: ${{ inputs.ignore_missing_alt }}
        INPUT_IGNORE_STATUS_CODES: ${{ inputs.ignore_status_codes }}
        INPUT_IGNORE_URLS: ${{ inputs.ignore_urls }}
        INPUT_IGNORE_NEW_FILES: ${{ inputs.ignore_new_files }}
        INPUT_SWAP_URLS: ${{ inputs.swap_urls }}
        INPUT_HOST: ${{ inputs.host }}
        INPUT_BASE_PATH: ${{ inputs.base_path }}
        INPUT_MAX_CONCURRENCY: ${{ inputs.max_concurrency }}
        INPUT_CONNECT_TIMEOUT: ${{ inputs.connect_timeout }}
        INPUT_FOLLOWLOCATION: ${{ inputs.followlocation }}
        INPUT_SSL_VERIFYPEER: ${{ inputs.ssl_verifypeer }}
        INPUT_SSL_VERIFYHOST: ${{ inputs.ssl_verifyhost }}
        INPUT_TIMEOUT: ${{ inputs.timeout }}
        INPUT_RETRIES: ${{ inputs.retries }}

branding:
  icon: link
  color: green
