name: Docker

on:
  pull_request:
  push:
    branches:
      - main
  release:
    types: [published]
  workflow_dispatch:

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup environment (release)
        if: ${{ github.event.release.tag_name != '' }}
        run: |
          echo "VERSION=${{ github.event.release.tag_name }}" >> $GITHUB_ENV
      - name: Setup environment (draft)
        if: ${{ github.event.release.tag_name == '' }}
        run: |
          echo "VERSION=latest" >> $GITHUB_ENV
      - name: Login to DockerHub
        uses: docker/login-action@v3.3.0
        if: ${{ github.ref == 'refs/heads/main' || github.event_name == 'release' }}
        with:
          username: althack
          password: ${{ secrets.DOCKER_TOKEN }}
      - name: Build and push docker image
        uses: docker/build-push-action@v6.9.0
        with:
          context: .
          file: ./Dockerfile
          tags: althack/htmlproofer:${{ env.VERSION }}
          push: ${{ github.ref == 'refs/heads/main' || github.event_name == 'release' }}
