name: Docs

on:
  pull_request:
  push:
    branches: [main]
  release:
    types: [published]
  workflow_dispatch:
  repository_dispatch:
    types: [publish-docs]

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: write
  pages: write
  id-token: write

# Cancel in-progress funs of the same workflow
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup environment (release)
        if: ${{ github.event.release.tag_name != '' }}
        run: |
          echo "VERSION=${{ github.event.release.tag_name }}" >> $GITHUB_ENV
          echo "DEFAULT_VERSION=${{ github.event.release.tag_name }}" >> $GITHUB_ENV
      - name: Setup environment (dev)
        if: ${{ github.event.release.tag_name == '' }}
        run: |
          echo "VERSION=dev" >> $GITHUB_ENV
          echo "DEFAULT_VERSION=" >> $GITHUB_ENV
      - name: Setup config
        uses: athackst/athackst.mkdocs@main
      - name: Build dev docs
        uses: athackst/mkdocs-simple-plugin@main
        with:
          version: ${{ env.VERSION }}
          default_version: ${{ env.DEFAULT_VERSION }}
          push: ${{ github.ref == 'refs/heads/main' || github.event_name == 'release' }}
      - name: Htmlproofer
        uses: ./
        with:
          directory: site
          swap_urls: |
            ^\/dev:
            ^\/v\d+\.\d+\.\d+:
