name: publish-docs

on:
  push:
    branches:
      - main
  workflow_dispatch:
  repository_dispatch:
    types: [publish-docs]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: MkDocs Simple action
        uses: athackst/mkdocs-simple-plugin@main
      - name: htmlproofer
        uses: athackst/htmlproofer-action@main
        with:
          directory: ./site
