name: Draft release

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  update_release_draft:
    runs-on: ubuntu-latest
    steps:
      # Drafts your next Release notes as Pull Requests are merged into "main"
      - uses: release-drafter/release-drafter@v5.23.0
        id: release-draft
        with:
          # (Optional) specify config name to use, relative to .github/. Default: release-drafter.yml
          config-name: release-drafter.yml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Login to DockerHub
        uses: docker/login-action@v2.2.0
        with:
          username: althack
          password: ${{ secrets.DOCKER_TOKEN }}
      - name: Build and push docker image
        uses: docker/build-push-action@v4.1.1
        with:
          context: .
          file: ./Dockerfile
          tags: althack/htmlproofer:latest
          push: true
